package com.itis.delivery.utils

enum class Categories {
    FRUITS,
    MEATS,
    VEGETABLES,
    FISH_AND_SEAFOOD,
    DAIRY_DESSERTS,
    EGGS,
    CEREAL_GRAINS_AND_BAKERY_PRODUCTS,
    PASTAS,
    NUTS_AND_DRIED_FRUITS,
    SPICES,
    VEGETABLE_OILS_AND_SAUCES,
    SWEETS_AND_CONFECTIONERY,
    NON_ALCOHOLIC_BEVERAGES,
    COFFEE_AND_TEA,
    BABY_FOODS
}